<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\SubArea;

// composer require laracasts/testdummy
// use Laracasts\TestDummy\Factory as TestDummy;

class SubAreaTableSeeder extends Seeder
{
    public function run()
    {
        $items =[

            ["area_id" => 1, "subarea_name" => "งามวงศ์วาน"],
            ["area_id" => 1, "subarea_name" => "แคราย"],
            ["area_id" => 1, "subarea_name" => "แจ้งวัฒนะ"],
            ["area_id" => 2, "subarea_name" => "ปิ่นเกล้า – บรมราชชนนี"],
            ["area_id" => 2, "subarea_name" => "เพชรเกษม – บางแค"],
            ["area_id" => 3, "subarea_name" => "ชิดลม – หลังสวน"],
            ["area_id" => 3, "subarea_name" => "ราชดำริ"],
            ["area_id" => 3, "subarea_name" => "เพลินจิต – วิทยุ"],
            ["area_id" => 4, "subarea_name" => "จตุรทิศ"],
            ["area_id" => 4, "subarea_name" => "ดินแดง"],
            ["area_id" => 4, "subarea_name" => "ราชปรารภ"],
            ["area_id" => 5, "subarea_name" => "ตลาดพลู – โพธิ์นิมิตร"],
            ["area_id" => 5, "subarea_name" => "บางหว้า"],
            ["area_id" => 5, "subarea_name" => "วุฒากาศ"],
            ["area_id" => 6, "subarea_name" => "ทองหล่อ"],
            ["area_id" => 6, "subarea_name" => "พระโขนง"],
            ["area_id" => 6, "subarea_name" => "เอกมัย"],
            ["area_id" => 7, "subarea_name" => "กรุงธนบุรี"],
            ["area_id" => 7, "subarea_name" => "วงเวียนใหญ่"],
            ["area_id" => 8, "subarea_name" => "กรุงเทพฯ-นนท์"],
            ["area_id" => 8, "subarea_name" => "ติวานนท์"],
            ["area_id" => 8, "subarea_name" => "บางซื่อ"],
            ["area_id" => 8, "subarea_name" => "ประชาชื่น"],
            ["area_id" => 8, "subarea_name" => "วงศ์สว่าง"],
            ["area_id" => 9, "subarea_name" => "บางนา-ตราด"],
            ["area_id" => 9, "subarea_name" => "ศรีนครินทร์"],
            ["area_id" => 10, "subarea_name" => "บางกรวย-ไทรน้อย"],
            ["area_id" => 10, "subarea_name" => "บางบัวทอง"],
            ["area_id" => 10, "subarea_name" => "วงแหวนตะวันตก (กาญจนาภิเษก)"],
            ["area_id" => 11, "subarea_name" => "พญาไท"],
            ["area_id" => 11, "subarea_name" => "ราชเทวี"],
            ["area_id" => 11, "subarea_name" => "สยาม"],
            ["area_id" => 11, "subarea_name" => "สามย่าน"],
            ["area_id" => 12, "subarea_name" => "พระราม 2"],
            ["area_id" => 12, "subarea_name" => "เทียนทะเล"],
            ["area_id" => 12, "subarea_name" => "เอกชัย – บางบอน"],
            ["area_id" => 13, "subarea_name" => "ลุมพินี – คลองเตย"],
            ["area_id" => 14, "subarea_name" => "นครปฐม"],
            ["area_id" => 14, "subarea_name" => "พิษณุโลก"],
            ["area_id" => 14, "subarea_name" => "สมุทรปราการ"],
            ["area_id" => 15, "subarea_name" => "ชลบุรี"],
            ["area_id" => 15, "subarea_name" => "บางแสน"],
            ["area_id" => 15, "subarea_name" => "พัทยา"],
            ["area_id" => 15, "subarea_name" => "ระยอง"],
            ["area_id" => 15, "subarea_name" => "ศรีราชา"],
            ["area_id" => 16, "subarea_name" => "ขอนแก่น"],
            ["area_id" => 16, "subarea_name" => "นครราชสีมา"],
            ["area_id" => 16, "subarea_name" => "อุดรธานี"],
            ["area_id" => 16, "subarea_name" => "เขาใหญ่"],
            ["area_id" => 17, "subarea_name" => "เชียงราย"],
            ["area_id" => 17, "subarea_name" => "เชียงใหม่"],
            ["area_id" => 18, "subarea_name" => "ชะอำ"],
            ["area_id" => 18, "subarea_name" => "ภูเก็ต"],
            ["area_id" => 18, "subarea_name" => "สุราษฎร์ธานี"],
            ["area_id" => 18, "subarea_name" => "หัวหิน"],
            ["area_id" => 18, "subarea_name" => "หาดใหญ่"],
            ["area_id" => 19, "subarea_name" => "รังสิต"],
            ["area_id" => 19, "subarea_name" => "ลำลูกกา"],
            ["area_id" => 20, "subarea_name" => "รัชดาภิเษก"],
            ["area_id" => 20, "subarea_name" => "สุทธิสาร"],
            ["area_id" => 20, "subarea_name" => "ห้วยขวาง – ประชาอุทิศ"],
            ["area_id" => 20, "subarea_name" => "เทียมร่วมมิตร"],
            ["area_id" => 21, "subarea_name" => "รัชโยธิน-เสนานิคม"],
            ["area_id" => 21, "subarea_name" => "สะพานใหม่"],
            ["area_id" => 22, "subarea_name" => "บางใหญ่"],
            ["area_id" => 22, "subarea_name" => "รัตนาธิเบศร์ตอนต้น"],
            ["area_id" => 22, "subarea_name" => "รัตนาธิเบศร์ตอนปลาย"],
            ["area_id" => 22, "subarea_name" => "สนามบินน้ำ"],
            ["area_id" => 23, "subarea_name" => "ราชพฤกษ์-กัลปพฤกษ์"],
            ["area_id" => 23, "subarea_name" => "ราชพฤกษ์-ชัยพฤกษ์"],
            ["area_id" => 23, "subarea_name" => "ราชพฤกษ์-นครอินทร์"],
            ["area_id" => 23, "subarea_name" => "ราชพฤกษ์-บรมราชชนนี"],
            ["area_id" => 23, "subarea_name" => "ราชพฤกษ์-รัตนาธิเบศร์"],
            ["area_id" => 24, "subarea_name" => "รามคำแหง"],
            ["area_id" => 24, "subarea_name" => "หัวหมาก – กรุงเทพกรีฑา"],
            ["area_id" => 24, "subarea_name" => "เสรีไทย"],
            ["area_id" => 25, "subarea_name" => "ปัญญาอินทรา"],
            ["area_id" => 25, "subarea_name" => "รามอินทรา"],
            ["area_id" => 25, "subarea_name" => "ลาดปลาเค้า"],
            ["area_id" => 26, "subarea_name" => "ร่มเกล้า – กิ่งแก้ว"],
            ["area_id" => 26, "subarea_name" => "ลาดกระบัง"],
            ["area_id" => 27, "subarea_name" => "ลาดพร้าว – วังหิน"],
            ["area_id" => 27, "subarea_name" => "ลาดพร้าวตอนต้น"],
            ["area_id" => 27, "subarea_name" => "ลาดพร้าวตอนปลาย"],
            ["area_id" => 28, "subarea_name" => "วัชรพล"],
            ["area_id" => 28, "subarea_name" => "สายไหม – หทัยราษฎร์"],
            ["area_id" => 29, "subarea_name" => "ดอนเมือง – สรงประภา"],
            ["area_id" => 29, "subarea_name" => "รัชวิภา"],
            ["area_id" => 29, "subarea_name" => "วิภาวดีรังสิต"],
            ["area_id" => 30, "subarea_name" => "อ้อมน้อย – พุทธมณฑลสาย 5"],
            ["area_id" => 31, "subarea_name" => "สำโรง – ปู่เจ้าสมิงพราย"],
            ["area_id" => 31, "subarea_name" => "เทพารักษ์ – แพรกษา"],
            ["area_id" => 32, "subarea_name" => "สาทร"],
            ["area_id" => 32, "subarea_name" => "สีลม – ศาลาแดง"],
            ["area_id" => 33, "subarea_name" => "ประชาอุทิศ"],
            ["area_id" => 33, "subarea_name" => "ราษฎร์บูรณะ"],
            ["area_id" => 33, "subarea_name" => "สุขสวัสดิ์"],
            ["area_id" => 34, "subarea_name" => "สะพานควาย"],
            ["area_id" => 34, "subarea_name" => "หมอชิต – จตุจักร"],
            ["area_id" => 34, "subarea_name" => "อารีย์"],
            ["area_id" => 35, "subarea_name" => "ลาซาล – แบริ่ง"],
            ["area_id" => 35, "subarea_name" => "อุดมสุข"],
            ["area_id" => 36, "subarea_name" => "นานา"],
            ["area_id" => 36, "subarea_name" => "พร้อมพงษ์"],
            ["area_id" => 36, "subarea_name" => "อโศก"],
            ["area_id" => 37, "subarea_name" => "บางจาก"],
            ["area_id" => 37, "subarea_name" => "ปุณณวิถี"],
            ["area_id" => 37, "subarea_name" => "อ่อนนุช"],
            ["area_id" => 38, "subarea_name" => "นวมินทร์"],
            ["area_id" => 38, "subarea_name" => "ประดิษฐ์มนูธรรม"],
            ["area_id" => 38, "subarea_name" => "ประเสริฐมนูกิจ"],
            ["area_id" => 39, "subarea_name" => "จันทน์-สาธุประดิษฐ์"],
            ["area_id" => 39, "subarea_name" => "นราธิวาสราชนครินทร์"],
            ["area_id" => 39, "subarea_name" => "พระราม 3"],
            ["area_id" => 39, "subarea_name" => "เจริญกรุง – เจริญราษฎร์"],
            ["area_id" => 40, "subarea_name" => "พระราม 9"],
            ["area_id" => 40, "subarea_name" => "พัฒนาการ"],
            ["area_id" => 40, "subarea_name" => "เพชรบุรี"]

//            ['id' => 1, "area_id" => 1, "subarea_name" => "งามวงศ์วาน"],
//            ['id' => 2, "area_id" => 1, "subarea_name" => "แคราย"],
//            ['id' => 3, "area_id" => 1, "subarea_name" => "แจ้งวัฒนะ"],
//            ['id' => 4, "area_id" => 2, "subarea_name" => "ปิ่นเกล้า – บรมราชชนนี"],
//            ['id' => 5, "area_id" => 2, "subarea_name" => "เพชรเกษม – บางแค"],
//            ['id' => 6, "area_id" => 3, "subarea_name" => "ชิดลม – หลังสวน"],
//            ['id' => 7, "area_id" => 3, "subarea_name" => "ราชดำริ"],
//            ['id' => 8, "area_id" => 3, "subarea_name" => "เพลินจิต – วิทยุ"],
//            ['id' => 9, "area_id" => 4, "subarea_name" => "จตุรทิศ"],
//            ['id' => 10, "area_id" => 4, "subarea_name" => "ดินแดง"],
//            ['id' => 11, "area_id" => 4, "subarea_name" => "ราชปรารภ"],
//            ['id' => 12, "area_id" => 5, "subarea_name" => "ตลาดพลู – โพธิ์นิมิตร"],
//            ['id' => 13, "area_id" => 5, "subarea_name" => "บางหว้า"],
//            ['id' => 14, "area_id" => 5, "subarea_name" => "วุฒากาศ"],
//            ['id' => 15, "area_id" => 6, "subarea_name" => "ทองหล่อ"],
//            ['id' => 16, "area_id" => 6, "subarea_name" => "พระโขนง"],
//            ['id' => 17, "area_id" => 6, "subarea_name" => "เอกมัย"],
//            ['id' => 18, "area_id" => 7, "subarea_name" => "กรุงธนบุรี"],
//            ['id' => 19, "area_id" => 7, "subarea_name" => "วงเวียนใหญ่"],
//            ['id' => 20, "area_id" => 8, "subarea_name" => "กรุงเทพฯ-นนท์"],
//            ['id' => 21, "area_id" => 8, "subarea_name" => "ติวานนท์"],
//            ['id' => 22, "area_id" => 8, "subarea_name" => "บางซื่อ"],
//            ['id' => 23, "area_id" => 8, "subarea_name" => "ประชาชื่น"],
//            ['id' => 24, "area_id" => 8, "subarea_name" => "วงศ์สว่าง"],
//            ['id' => 25, "area_id" => 9, "subarea_name" => "บางนา-ตราด"],
//            ['id' => 26, "area_id" => 9, "subarea_name" => "ศรีนครินทร์"],
//            ['id' => 27, "area_id" => 10, "subarea_name" => "บางกรวย-ไทรน้อย"],
//            ['id' => 28, "area_id" => 10, "subarea_name" => "บางบัวทอง"],
//            ['id' => 29, "area_id" => 10, "subarea_name" => "วงแหวนตะวันตก (กาญจนาภิเษก)"],
//            ['id' => 30, "area_id" => 11, "subarea_name" => "พญาไท"],
//            ['id' => 31, "area_id" => 11, "subarea_name" => "ราชเทวี"],
//            ['id' => 32, "area_id" => 11, "subarea_name" => "สยาม"],
//            ['id' => 33, "area_id" => 11, "subarea_name" => "สามย่าน"],
//            ['id' => 34, "area_id" => 12, "subarea_name" => "พระราม 2"],
//            ['id' => 35, "area_id" => 12, "subarea_name" => "เทียนทะเล"],
//            ['id' => 36, "area_id" => 12, "subarea_name" => "เอกชัย – บางบอน"],
//            ['id' => 37, "area_id" => 13, "subarea_name" => "ลุมพินี – คลองเตย"],
//            ['id' => 38, "area_id" => 14, "subarea_name" => "นครปฐม"],
//            ['id' => 39, "area_id" => 14, "subarea_name" => "พิษณุโลก"],
//            ['id' => 40, "area_id" => 14, "subarea_name" => "สมุทรปราการ"],
//            ['id' => 41, "area_id" => 15, "subarea_name" => "ชลบุรี"],
//            ['id' => 42, "area_id" => 15, "subarea_name" => "บางแสน"],
//            ['id' => 43, "area_id" => 15, "subarea_name" => "พัทยา"],
//            ['id' => 44, "area_id" => 15, "subarea_name" => "ระยอง"],
//            ['id' => 45, "area_id" => 15, "subarea_name" => "ศรีราชา"],
//            ['id' => 46, "area_id" => 16, "subarea_name" => "ขอนแก่น"],
//            ['id' => 47, "area_id" => 16, "subarea_name" => "นครราชสีมา"],
//            ['id' => 48, "area_id" => 16, "subarea_name" => "อุดรธานี"],
//            ['id' => 49, "area_id" => 16, "subarea_name" => "เขาใหญ่"],
//            ['id' => 50, "area_id" => 17, "subarea_name" => "เชียงราย"],
//            ['id' => 51, "area_id" => 17, "subarea_name" => "เชียงใหม่"],
//            ['id' => 52, "area_id" => 18, "subarea_name" => "ชะอำ"],
//            ['id' => 53, "area_id" => 18, "subarea_name" => "ภูเก็ต"],
//            ['id' => 54, "area_id" => 18, "subarea_name" => "สุราษฎร์ธานี"],
//            ['id' => 55, "area_id" => 18, "subarea_name" => "หัวหิน"],
//            ['id' => 56, "area_id" => 18, "subarea_name" => "หาดใหญ่"],
//            ['id' => 57, "area_id" => 19, "subarea_name" => "รังสิต"],
//            ['id' => 58, "area_id" => 19, "subarea_name" => "ลำลูกกา"],
//            ['id' => 59, "area_id" => 20, "subarea_name" => "รัชดาภิเษก"],
//            ['id' => 60, "area_id" => 20, "subarea_name" => "สุทธิสาร"],
//            ['id' => 61, "area_id" => 20, "subarea_name" => "ห้วยขวาง – ประชาอุทิศ"],
//            ['id' => 62, "area_id" => 20, "subarea_name" => "เทียมร่วมมิตร"],
//            ['id' => 63, "area_id" => 21, "subarea_name" => "รัชโยธิน-เสนานิคม"],
//            ['id' => 64, "area_id" => 21, "subarea_name" => "สะพานใหม่"],
//            ['id' => 65, "area_id" => 22, "subarea_name" => "บางใหญ่"],
//            ['id' => 66, "area_id" => 22, "subarea_name" => "รัตนาธิเบศร์ตอนต้น"],
//            ['id' => 67, "area_id" => 22, "subarea_name" => "รัตนาธิเบศร์ตอนปลาย"],
//            ['id' => 68, "area_id" => 22, "subarea_name" => "สนามบินน้ำ"],
//            ['id' => 69, "area_id" => 23, "subarea_name" => "ราชพฤกษ์-กัลปพฤกษ์"],
//            ['id' => 70, "area_id" => 23, "subarea_name" => "ราชพฤกษ์-ชัยพฤกษ์"],
//            ['id' => 71, "area_id" => 23, "subarea_name" => "ราชพฤกษ์-นครอินทร์"],
//            ['id' => 72, "area_id" => 23, "subarea_name" => "ราชพฤกษ์-บรมราชชนนี"],
//            ['id' => 73, "area_id" => 23, "subarea_name" => "ราชพฤกษ์-รัตนาธิเบศร์"],
//            ['id' => 74, "area_id" => 24, "subarea_name" => "รามคำแหง"],
//            ['id' => 75, "area_id" => 24, "subarea_name" => "หัวหมาก – กรุงเทพกรีฑา"],
//            ['id' => 76, "area_id" => 24, "subarea_name" => "เสรีไทย"],
//            ['id' => 77, "area_id" => 25, "subarea_name" => "ปัญญาอินทรา"],
//            ['id' => 78, "area_id" => 25, "subarea_name" => "รามอินทรา"],
//            ['id' => 79, "area_id" => 25, "subarea_name" => "ลาดปลาเค้า"],
//            ['id' => 80, "area_id" => 26, "subarea_name" => "ร่มเกล้า – กิ่งแก้ว"],
//            ['id' => 81, "area_id" => 26, "subarea_name" => "ลาดกระบัง"],
//            ['id' => 82, "area_id" => 27, "subarea_name" => "ลาดพร้าว – วังหิน"],
//            ['id' => 83, "area_id" => 27, "subarea_name" => "ลาดพร้าวตอนต้น"],
//            ['id' => 84, "area_id" => 27, "subarea_name" => "ลาดพร้าวตอนปลาย"],
//            ['id' => 85, "area_id" => 28, "subarea_name" => "วัชรพล"],
//            ['id' => 86, "area_id" => 28, "subarea_name" => "สายไหม – หทัยราษฎร์"],
//            ['id' => 87, "area_id" => 29, "subarea_name" => "ดอนเมือง – สรงประภา"],
//            ['id' => 88, "area_id" => 29, "subarea_name" => "รัชวิภา"],
//            ['id' => 89, "area_id" => 29, "subarea_name" => "วิภาวดีรังสิต"],
//            ['id' => 90, "area_id" => 30, "subarea_name" => "อ้อมน้อย – พุทธมณฑลสาย 5"],
//            ['id' => 91, "area_id" => 31, "subarea_name" => "สำโรง – ปู่เจ้าสมิงพราย"],
//            ['id' => 92, "area_id" => 31, "subarea_name" => "เทพารักษ์ – แพรกษา"],
//            ['id' => 93, "area_id" => 32, "subarea_name" => "สาทร"],
//            ['id' => 94, "area_id" => 32, "subarea_name" => "สีลม – ศาลาแดง"],
//            ['id' => 95, "area_id" => 33, "subarea_name" => "ประชาอุทิศ"],
//            ['id' => 96, "area_id" => 33, "subarea_name" => "ราษฎร์บูรณะ"],
//            ['id' => 97, "area_id" => 33, "subarea_name" => "สุขสวัสดิ์"],
//            ['id' => 98, "area_id" => 34, "subarea_name" => "สะพานควาย"],
//            ['id' => 99, "area_id" => 34, "subarea_name" => "หมอชิต – จตุจักร"],
//            ['id' => 100, "area_id" => 34, "subarea_name" => "อารีย์"],
//            ['id' => 101, "area_id" => 35, "subarea_name" => "ลาซาล – แบริ่ง"],
//            ['id' => 102, "area_id" => 35, "subarea_name" => "อุดมสุข"],
//            ['id' => 103, "area_id" => 36, "subarea_name" => "นานา"],
//            ['id' => 104, "area_id" => 36, "subarea_name" => "พร้อมพงษ์"],
//            ['id' => 105, "area_id" => 36, "subarea_name" => "อโศก"],
//            ['id' => 106, "area_id" => 37, "subarea_name" => "บางจาก"],
//            ['id' => 107, "area_id" => 37, "subarea_name" => "ปุณณวิถี"],
//            ['id' => 108, "area_id" => 37, "subarea_name" => "อ่อนนุช"],
//            ['id' => 109, "area_id" => 38, "subarea_name" => "นวมินทร์"],
//            ['id' => 110, "area_id" => 38, "subarea_name" => "ประดิษฐ์มนูธรรม"],
//            ['id' => 111, "area_id" => 38, "subarea_name" => "ประเสริฐมนูกิจ"],
//            ['id' => 112, "area_id" => 39, "subarea_name" => "จันทน์-สาธุประดิษฐ์"],
//            ['id' => 113, "area_id" => 39, "subarea_name" => "นราธิวาสราชนครินทร์"],
//            ['id' => 114, "area_id" => 39, "subarea_name" => "พระราม 3"],
//            ['id' => 115, "area_id" => 39, "subarea_name" => "เจริญกรุง – เจริญราษฎร์"],
//            ['id' => 116, "area_id" => 40, "subarea_name" => "พระราม 9"],
//            ['id' => 117, "area_id" => 40, "subarea_name" => "พัฒนาการ"],
//            ['id' => 118, "area_id" => 40, "subarea_name" => "เพชรบุรี"]

        ];

        DB::table('subarea')->delete();
        foreach ($items as $item){
            SubArea::create($item);
        }
    }
}
